//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganicGridTerrain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfPoint xmlns:xsi=\"http://www.w3.o" +
            "rg/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <Po" +
            "int>\r\n    <X>22</X>\r\n    <Y>5</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>21</X>\r\n    <Y>" +
            "5</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>18</X>\r\n    <Y>5</Y>\r\n  </Point>\r\n  <Point>" +
            "\r\n    <X>17</X>\r\n    <Y>5</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>15</X>\r\n    <Y>5</Y" +
            ">\r\n  </Point>\r\n  <Point>\r\n    <X>14</X>\r\n    <Y>5</Y>\r\n  </Point>\r\n  <Point>\r\n  " +
            "  <X>12</X>\r\n    <Y>5</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>11</X>\r\n    <Y>5</Y>\r\n " +
            " </Point>\r\n  <Point>\r\n    <X>10</X>\r\n    <Y>5</Y>\r\n  </Point>\r\n  <Point>\r\n    <X" +
            ">8</X>\r\n    <Y>5</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>4</X>\r\n    <Y>5</Y>\r\n  </Poi" +
            "nt>\r\n  <Point>\r\n    <X>3</X>\r\n    <Y>5</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>2</X>\r" +
            "\n    <Y>5</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>1</X>\r\n    <Y>5</Y>\r\n  </Point>\r\n  " +
            "<Point>\r\n    <X>9</X>\r\n    <Y>5</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>23</X>\r\n    <" +
            "Y>5</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>22</X>\r\n    <Y>4</Y>\r\n  </Point>\r\n  <Poin" +
            "t>\r\n    <X>19</X>\r\n    <Y>4</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>18</X>\r\n    <Y>4<" +
            "/Y>\r\n  </Point>\r\n  <Point>\r\n    <X>20</X>\r\n    <Y>4</Y>\r\n  </Point>\r\n  <Point>\r\n" +
            "    <X>21</X>\r\n    <Y>4</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>20</X>\r\n    <Y>3</Y>\r" +
            "\n  </Point>\r\n  <Point>\r\n    <X>19</X>\r\n    <Y>3</Y>\r\n  </Point>\r\n  <Point>\r\n    " +
            "<X>13</X>\r\n    <Y>4</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>12</X>\r\n    <Y>4</Y>\r\n  <" +
            "/Point>\r\n  <Point>\r\n    <X>11</X>\r\n    <Y>4</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>1" +
            "2</X>\r\n    <Y>3</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>7</X>\r\n    <Y>4</Y>\r\n  </Poin" +
            "t>\r\n  <Point>\r\n    <X>6</X>\r\n    <Y>4</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>6</X>\r\n" +
            "    <Y>3</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>6</X>\r\n    <Y>2</Y>\r\n  </Point>\r\n  <" +
            "Point>\r\n    <X>7</X>\r\n    <Y>2</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>7</X>\r\n    <Y>" +
            "3</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>5</X>\r\n    <Y>4</Y>\r\n  </Point>\r\n  <Point>\r" +
            "\n    <X>3</X>\r\n    <Y>4</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>6</X>\r\n    <Y>1</Y>\r\n" +
            "  </Point>\r\n  <Point>\r\n    <X>18</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r\n    <" +
            "X>17</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>14</X>\r\n    <Y>6</Y>\r\n  </" +
            "Point>\r\n  <Point>\r\n    <X>12</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>11" +
            "</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>10</X>\r\n    <Y>6</Y>\r\n  </Poin" +
            "t>\r\n  <Point>\r\n    <X>9</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>3</X>\r\n" +
            "    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>1</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <" +
            "Point>\r\n    <X>2</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>4</X>\r\n    <Y>" +
            "6</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>8</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r" +
            "\n    <X>15</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>23</X>\r\n    <Y>6</Y>" +
            "\r\n  </Point>\r\n  <Point>\r\n    <X>1</X>\r\n    <Y>9</Y>\r\n  </Point>\r\n  <Point>\r\n    " +
            "<X>1</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>2</X>\r\n    <Y>7</Y>\r\n  </" +
            "Point>\r\n  <Point>\r\n    <X>2</X>\r\n    <Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>2</" +
            "X>\r\n    <Y>9</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>3</X>\r\n    <Y>8</Y>\r\n  </Point>\r" +
            "\n  <Point>\r\n    <X>3</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>23</X>\r\n  " +
            "  <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>22</X>\r\n    <Y>9</Y>\r\n  </Point>\r\n  <P" +
            "oint>\r\n    <X>22</X>\r\n    <Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>21</X>\r\n    <Y" +
            ">10</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>21</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Poin" +
            "t>\r\n    <X>21</X>\r\n    <Y>9</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>20</X>\r\n    <Y>7<" +
            "/Y>\r\n  </Point>\r\n  <Point>\r\n    <X>20</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r" +
            "\n    <X>19</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>19</X>\r\n    <Y>8</Y>" +
            "\r\n  </Point>\r\n  <Point>\r\n    <X>19</X>\r\n    <Y>9</Y>\r\n  </Point>\r\n  <Point>\r\n   " +
            " <X>19</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>18</X>\r\n    <Y>7</Y>\r\n " +
            " </Point>\r\n  <Point>\r\n    <X>17</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X" +
            ">16</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>15</X>\r\n    <Y>7</Y>\r\n  </P" +
            "oint>\r\n  <Point>\r\n    <X>15</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>14" +
            "</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>14</X>\r\n    <Y>9</Y>\r\n  </Poi" +
            "nt>\r\n  <Point>\r\n    <X>14</X>\r\n    <Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>14</X" +
            ">\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>13</X>\r\n    <Y>8</Y>\r\n  </Point>\r" +
            "\n  <Point>\r\n    <X>13</X>\r\n    <Y>9</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>13</X>\r\n " +
            "   <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>12</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n " +
            " <Point>\r\n    <X>11</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>11</X>\r\n   " +
            " <Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>11</X>\r\n    <Y>9</Y>\r\n  </Point>\r\n  <Po" +
            "int>\r\n    <X>11</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>10</X>\r\n    <Y" +
            ">9</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>9</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point" +
            ">\r\n    <X>10</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>8</X>\r\n    <Y>10<" +
            "/Y>\r\n  </Point>\r\n  <Point>\r\n    <X>6</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n" +
            "    <X>5</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>5</X>\r\n    <Y>7</Y>\r\n" +
            "  </Point>\r\n  <Point>\r\n    <X>7</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X" +
            ">8</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>9</X>\r\n    <Y>7</Y>\r\n  </Poi" +
            "nt>\r\n  <Point>\r\n    <X>10</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>10</X" +
            ">\r\n    <Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>9</X>\r\n    <Y>8</Y>\r\n  </Point>\r\n" +
            "  <Point>\r\n    <X>7</X>\r\n    <Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>6</X>\r\n    " +
            "<Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>6</X>\r\n    <Y>9</Y>\r\n  </Point>\r\n  <Poin" +
            "t>\r\n    <X>9</X>\r\n    <Y>9</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>1</X>\r\n    <Y>11</" +
            "Y>\r\n  </Point>\r\n  <Point>\r\n    <X>2</X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n " +
            "   <X>3</X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>5</X>\r\n    <Y>11</Y>\r\n" +
            "  </Point>\r\n  <Point>\r\n    <X>4</X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <" +
            "X>6</X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>8</X>\r\n    <Y>11</Y>\r\n  </" +
            "Point>\r\n  <Point>\r\n    <X>9</X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>10" +
            "</X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>11</X>\r\n    <Y>11</Y>\r\n  </Po" +
            "int>\r\n  <Point>\r\n    <X>14</X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>15<" +
            "/X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>17</X>\r\n    <Y>11</Y>\r\n  </Poi" +
            "nt>\r\n  <Point>\r\n    <X>18</X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>22</" +
            "X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>21</X>\r\n    <Y>11</Y>\r\n  </Poin" +
            "t>\r\n  <Point>\r\n    <X>20</X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>19</X" +
            ">\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>16</X>\r\n    <Y>11</Y>\r\n  </Point" +
            ">\r\n  <Point>\r\n    <X>13</X>\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>12</X>" +
            "\r\n    <Y>11</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>13</X>\r\n    <Y>3</Y>\r\n  </Point>\r" +
            "\n  <Point>\r\n    <X>18</X>\r\n    <Y>3</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>2</X>\r\n  " +
            "  <Y>4</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>1</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Po" +
            "int>\r\n    <X>5</X>\r\n    <Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>13</X>\r\n    <Y>5" +
            "</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>5</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r\n" +
            "    <X>6</X>\r\n    <Y>7</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>19</X>\r\n    <Y>5</Y>\r\n" +
            "  </Point>\r\n  <Point>\r\n    <X>16</X>\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n    " +
            "<X>16</X>\r\n    <Y>9</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>16</X>\r\n    <Y>8</Y>\r\n  <" +
            "/Point>\r\n  <Point>\r\n    <X>17</X>\r\n    <Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>1" +
            "8</X>\r\n    <Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>15</X>\r\n    <Y>8</Y>\r\n  </Poi" +
            "nt>\r\n  <Point>\r\n    <X>7</X>\r\n    <Y>6</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>22</X>" +
            "\r\n    <Y>10</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>23</X>\r\n    <Y>9</Y>\r\n  </Point>\r" +
            "\n  <Point>\r\n    <X>23</X>\r\n    <Y>8</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>10</X>\r\n " +
            "   <Y>12</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>11</X>\r\n    <Y>12</Y>\r\n  </Point>\r\n " +
            " <Point>\r\n    <X>12</X>\r\n    <Y>12</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>13</X>\r\n  " +
            "  <Y>12</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>12</X>\r\n    <Y>13</Y>\r\n  </Point>\r\n  " +
            "<Point>\r\n    <X>13</X>\r\n    <Y>13</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>11</X>\r\n   " +
            " <Y>13</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>16</X>\r\n    <Y>12</Y>\r\n  </Point>\r\n  <" +
            "Point>\r\n    <X>17</X>\r\n    <Y>12</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>21</X>\r\n    " +
            "<Y>12</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>4</X>\r\n    <Y>12</Y>\r\n  </Point>\r\n  <Po" +
            "int>\r\n    <X>4</X>\r\n    <Y>13</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>5</X>\r\n    <Y>1" +
            "3</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>6</X>\r\n    <Y>13</Y>\r\n  </Point>\r\n  <Point>" +
            "\r\n    <X>7</X>\r\n    <Y>12</Y>\r\n  </Point>\r\n  <Point>\r\n    <X>21</X>\r\n    <Y>13</" +
            "Y>\r\n  </Point>\r\n  <Point>\r\n    <X>20</X>\r\n    <Y>13</Y>\r\n  </Point>\r\n  <Point>\r\n" +
            "    <X>20</X>\r\n    <Y>12</Y>\r\n  </Point>\r\n</ArrayOfPoint>")]
        public System.Drawing.Point[] Slot {
            get {
                return ((System.Drawing.Point[])(this["Slot"]));
            }
            set {
                this["Slot"] = value;
            }
        }
    }
}
